---
title: "CCL_CC_Clean"
author: "Olivia Henning"
date: "11/23/2020"
output: html_document
---

```
This code serves to sort Credit Card Data from Boston University's travel credit card to remove non-flight related activity and to remove duplicate flights.
```

# Read in Data

```{r}  
dat_raw = read.csv("Credit_Card_Flight_Data.csv", header = TRUE) ## loading in data

```

# Subsetting

```{r}  
dat_years = subset(dat_raw, Departure_Year==2017 | Departure_Year==2018 | Departure_Year==2019, select=c(Leg:Service.Category.1))  ##  subset 2017-2019 data

dat_years

```
```{r}  
library(tidyverse)

remove_sf = subset(dat_years, Service.Category.1=="") ## remove service fees

remove_XXX = subset(remove_sf, Destination.Code != "XXX")

remove_XXX

```
```{r}  
#remove_legs = subset(remove_sf, remove_sf$Ticket.Number, select = "Leg01")

#remove_sf[!duplicated(remove_sf$Ticket.Number), ]


#if (remove_sf$Ticket.Number != unique){
#select("Leg01"")
#}
  # combining flights w multiple legs (if ticket numbers are the same...)

#remove_legs = subset(remove_XXX, remove_XXX$Leg == "Leg01")  ## remove second legs

#remove_legs

# do we want to remove legs? or treat all round trip flights as one-way individual flights?
```

```{r}  
dat_concur = read.csv("Concur_Data.csv", header = TRUE) ## loading in CONCUR data

as.Date(dat_concur$Departure.Date)  ## changing text dates to number dates

#if (dat_concur$Flight.Number==dat_years$Flight.Number AND #dat_concur$Departure.Station.Code==dat_years$Origination.Airport.CD) {
#statement
#}  

#dups_removed = dat_years[!(dat_concur$Flight.Number == dat_years$Flight.Number & dat_concur$Arrival.Station.Code == dat_years$Destination.Code),]


#duplicates = dat_concur$Flight.Number == dat_years$Flight.Number & dat_concur$Arrival.Station.Code == dat_years$Destination.Code

repeat_flights = as.character(dat_concur$Flight.Number) != as.character(dat_years$Flight.Number) & as.character(dat_concur$Arrival.Station.Code) != as.character(dat_years$Destination.Code) & as.Date(dat_concur$Departure.Date) != as.Date(dat_years$Departure.Date)

subset(dat_years, repeat_flights) ## remove repeat flights in CC data



```




